**Women Cloth Reviews Prediction with multi Nomial Naive bayes**

The multinomial Naive Bayes classifier is suitable for classification with discrete features(e.g., Word counts for text classification).The multinomial distribution normally requires integer feature counts.However, in practice, fractional counts such as tf-idf may also work.

In [ ]:
#Import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("https://github.com/AFAgarap/ecommerce-reviews-analysis/raw/master/Womens%20Clothing%20E-Commerce%20Reviews.csv")
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [ ]:
df.shape

(23486, 11)

In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df.shape

(23486, 11)

In [ ]:
#df[df['Review Text']=='']=np.NaN

In [ ]:
df['Review Text'].fillna('No Review',inplace=True)

In [ ]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [ ]:
df['Review Text'][1]

'Love this dress!  it\'s sooo pretty.  i happened to find it in a store, and i\'m glad i did bc i never would have ordered it online bc it\'s petite.  i bought a petite and am 5\'8".  i love the length on me- hits just a little below the knee.  would definitely be a true midi on someone who is truly petite.'

In [ ]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [40]:
y=df['Rating']

In [60]:
x=df['Review Text']

In [61]:
df['Review Text'].value_counts()

No Review                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 845
Perfect fit and i've gotten so many compliments. i buy all my suits from here now!                                                                                                                                                                                                                                                                                                                                                                                                                        

In [62]:
df['Rating'].value_counts()

5    13131
4     5077
3     2871
2     1565
1      842
Name: Rating, dtype: int64

In [63]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=1)

In [64]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

**Get Feature text conversion to tokens**

In [65]:
from sklearn.feature_extraction.text import CountVectorizer

In [66]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [67]:
x_train=cv.fit_transform(x_train)

In [68]:
cv.get_feature_names_out()

array(['00 petite', '10 12', '10 bought', ..., 'yellow color',
       'yoga pants', 'zipper little'], dtype=object)

In [69]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [70]:
x_test=cv.fit_transform(x_test)

In [72]:
cv.get_feature_names_out()

array(['10 10', '10 12', '10 bought', ..., 'yes runs', 'yesterday store',
       'yoga pants'], dtype=object)

In [73]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

**Get Model Train**

In [74]:
from sklearn.naive_bayes import MultinomialNB

In [75]:
model=MultinomialNB()

In [76]:
model.fit(x_train,y_train)

MultinomialNB()

In [77]:
y_pred=model.predict(x_test)

In [78]:
y_pred

array([5, 5, 5, ..., 3, 5, 3])

In [79]:
y_pred.shape

(7046,)

**Get Probability of Each predicted Class**

In [80]:
model.predict_proba(x_test)

array([[0.09702981, 0.00331734, 0.06004331, 0.17649633, 0.66311321],
       [0.03621697, 0.08911341, 0.10433348, 0.22074678, 0.54958936],
       [0.00936731, 0.00504685, 0.07692157, 0.37867867, 0.5299856 ],
       ...,
       [0.05650503, 0.20863936, 0.48952467, 0.17815569, 0.06717525],
       [0.00628721, 0.0101665 , 0.05822352, 0.30197997, 0.6233428 ],
       [0.01959642, 0.12669601, 0.50287465, 0.0114259 , 0.33940703]])

In [81]:
from sklearn.metrics import confusion_matrix,classification_report

In [82]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.02      0.05      0.02       253
           2       0.06      0.07      0.06       470
           3       0.14      0.13      0.14       861
           4       0.22      0.18      0.20      1523
           5       0.57      0.53      0.55      3939

    accuracy                           0.36      7046
   macro avg       0.20      0.19      0.19      7046
weighted avg       0.39      0.36      0.37      7046



In [84]:
print(confusion_matrix(y_test,y_pred))

[[  12   14   26   55  146]
 [  41   31   51  112  235]
 [  81   68  114  165  433]
 [ 184  116  174  278  771]
 [ 464  301  443  654 2077]]


**Recategories Ratings as poor(0) and good(1)**

In [86]:
df['Rating'].value_counts()

5    13131
4     5077
3     2871
2     1565
1      842
Name: Rating, dtype: int64

In [88]:
df.replace({'Rating':{'1':0,'2':0,'3':0,'4':1,'5':1}},inplace=True)

In [89]:
y=df['Rating']

In [92]:
x=df['Review Text']

In [93]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=1)

In [94]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((18788,), (4698,), (18788,), (4698,))

In [95]:
from sklearn.feature_extraction.text import CountVectorizer

In [96]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [97]:
x_train=cv.fit_transform(x_train)

In [99]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [100]:
x_test=cv.fit_transform(x_test)

**Get model Re-train**

In [101]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

**Get model Prediction**

In [102]:
y_pred=model.predict(x_test)

In [103]:
y_pred

array([5, 5, 3, ..., 2, 5, 5])

In [104]:
y_pred.shape

(4698,)

In [105]:
from sklearn.metrics import confusion_matrix,classification_report

In [106]:
print(confusion_matrix(y_test,y_pred))

[[  16   14   22   30   86]
 [  29   26   44   61  153]
 [  75   42   75  102  280]
 [ 114   83  125  209  485]
 [ 283  168  256  472 1448]]


In [107]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.03      0.10      0.05       168
           2       0.08      0.08      0.08       313
           3       0.14      0.13      0.14       574
           4       0.24      0.21      0.22      1016
           5       0.59      0.55      0.57      2627

    accuracy                           0.38      4698
   macro avg       0.22      0.21      0.21      4698
weighted avg       0.41      0.38      0.39      4698

